### ISSUE TITLE
Uncaught (in promise) Error: Unsupported color space conversion, "1" to "srgb-linear"

### ISSUE THREAD

**Issue by QSYSMoric** [pixiv/three-vrm#1474]
I encounter this error when using Vue to build a project and import a VRM model：
three.module.js:1663 
 Uncaught (in promise) Error: Unsupported color space conversion, "1" to "srgb-linear".
    at Object.convert (three.module.js:1663:10)
    at Object.toWorkingColorSpace (three.module.js:1679:15)
    at Color.setRGB (three.module.js:9005:19)
    at GLTFParser.loadMaterial (GLTFLoader.js:3483:42)
    at GLTFLoader.js:2761:38
    at GLTFParser._invokeOne (GLTFLoader.js:2678:19)
    at GLTFParser.getDependency (GLTFLoader.js:2759:24)
    at GLTFParser.loadMesh (GLTFLoader.js:3620:12)
    at _MToonMaterialLoaderPlugin2.<anonymous> (MToonMaterialLoaderPlugin.ts:147:38)
    at Generator.next (<anonymous>)
This will cause me to be unable to load the model
I tried to replicate this question:
[three_vrm](https://github.com/QSYSMoric/three_vrm.git)

**Comment by 0b5vr** [comment]
This should be fixed in `three@0.156.1`, [This PR](https://github.com/mrdoob/three.js/pull/26691).

Please try bumping your Three.js.
