### ISSUE TITLE
new VRMExpressionTextureTransformBind() throws exception when given MToonMaterial

### ISSUE THREAD

**Issue by alankent** [pixiv/three-vrm#1541]
I am trying to add my own VRMExpressionTextureTransformBind to a VRM model, so I can tile the face texture (e.g. have a standard and blush version of the texture, then use scale & offset to select which part of the material to use). I have done this in Unity successfully, but I am trying to it in JavaScript now.

When I call `new VRMExpressionTextureTransformBind(material, scale, offset)` with a MToolMaterial (the ones from the loaded VRM file), I get the following exception:

```
TypeError: Cannot read properties of undefined (reading 'isMeshStandardMaterial')
    at eval (three-vrm.module.js:766:28)
    at Array.find (<anonymous>)
    at new VRMExpressionTextureTransformBind (three-vrm.module.js:765:105)
    at eval (loadCharacterModel.js:190:28)
    at eval (GLTFLoader.js:110:15)
    at eval (GLTFLoader.js:1453:9)
```

It appears the following is the problem:

```
...find( ([distinguisher]) => {
            return material[distinguisher] === true;
        }
```

Note: isMToonMaterial is a getter method, and not a property (if that matters). But it is failing on isMeshStandardMaterial - that property is not set (because its a MToonMaterial).

Line 765 in the browser is:

```
class VRMExpressionTextureTransformBind {
    constructor({material, scale, offset, }) {
        var _a, _b;
        this.material = material;
        this.scale = scale;
        this.offset = offset;
        const propertyNames = (_a = Object.entries(VRMExpressionTextureTransformBind._propertyNamesMap).find( ([distinguisher]) => { // Line 765
            return material[distinguisher] === true;
        }
        )) === null || _a === void 0 ? void 0 : _a[1];
```

Here is a snippet of the code I am trying to do. This is in the load code (after I load the VRM model, I am trying to immediately add a new expression as an experiment. (I want to save it as a custom expression.)

```
            const customExpressionName = 'sideways';
            const expression = new VRMExpression(customExpressionName);

            const materials = [];
            glbModel.vrm.scene.traverse((node) => {
              if (node.isMesh) {
                const mat = node.material;
                if (mat && mat.map) {
                  materials.push(mat);
                }
              }
            });

            for (const material of materials) {
              const scale = new Vector2(1, 1);
              const offset = new Vector2(0.5, 1);
              // The following line throws an exception. The Material is a MToolMaterial.
              const bind = new VRMExpressionTextureTransformBind(material, scale, offset);
              expression.addBind(bind);
            }

            vrm.expressionManager.registerExpression(expression);
```

ChatGPT suggests the following change - check distinguisher is in material before the array access which throws an exception.

```
const propertyNames = Object.entries(VRMExpressionTextureTransformBind._propertyNamesMap).find(
  ([distinguisher]) => distinguisher in material && material[distinguisher] === true
);
```

**Comment by alankent** [comment]
D'oh! Found my problem. The constructor has {} around what I thought the arguments were. Sigh.
